unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DeliveryInstallationStatus__c</fullName>
        <label>Delivery/Installation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Yet to begin</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ProjectRESTService.cls
@RestResource(urlMapping = '/project/*')
global class ProjectRESTService {
    
    @HttpPost
    global static String postProjectData(String ProjectRef, String ProjectName, 
                                         String OpportunityId, Date StartDate, 
                                         Date EndDate, Double Amount, String Status) {
                                             
                                             
      List<Project__c> projects = [SELECT Billable_Amount__c, End_Date__c, 
                                   Id, Name, Opportunity__c, 
                                   ProjectRef__c, Start_Date__c, Status__c 
                                   FROM Project__c WHERE ProjectRef__c = :ProjectRef];
                                             
      Project__c project = new Project__c();

                 if(projects.size() > 0) {
                         project = projects.get(0);
                      }
           
        SavePoint sp = Database.setSavepoint();
                                             
        try {
                      
            project.Opportunity__c = OpportunityId;
            project.Billable_Amount__c = Amount;
            project.End_Date__c = EndDate;
            project.Start_Date__c = StartDate;
            project.Name = ProjectName;
            project.ProjectRef__c = ProjectRef;
            project.Status__c = Status;
            
            upsert project;

          Opportunity opportunity = [SELECT Id, DeliveryInstallationStatus__c FROM Opportunity WHERE Id = :OpportunityId];

          opportunity.DeliveryInstallationStatus__c = 'In progress';

          update opportunity;

          return 'OK';

      }

      catch(exception ex){

          Database.rollback(sp);

          return 'Upsert failed';

      }

   }

}