unpackaged/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/BillingCalloutServiceTest.cls
@isTest
private class BillingCalloutServiceTest {
    
    @testSetup static void setupProject(){
        
        Opportunity oppo = new Opportunity(
            Name = 'TestOpp',
            CloseDate = Date.today(),
            StageName = 'Prospecting'
        );
        
        insert oppo;
        
        Project__c proj = new Project__c(
            Name = 'TestProj',
            Billable_Amount__c = 1000,       
            ProjectRef__c = 'TestRef',
            Status__c = 'Running',
            Opportunity__c = oppo.Id
        );
        
        
        insert proj;
        
        ServiceCredentials__c serviceCredentials = new ServiceCredentials__c(
            
            Name = 'BillingServiceCredential',
            Username__c = 'user1',
            Password__c = 'pass1'
        );
        
        insert serviceCredentials;
        
    }
    
    @isTest static void testCalloutSuccess(){
        
        Test.setMock(WebServiceMock.class, new BillingCalloutServiceMock()); 
        
        List<Project__c> prof = [SELECT Status__C 
                                 FROM Project__c 
                                 WHERE ProjectRef__c = 'TestRef'];
        
        System.assertEquals(1, prof.size());
        
        Test.startTest(); 
        
        prof[0].Status__c = 'Billable';
        
        update prof;
        
        Test.stopTest();
        
        prof = [SELECT Status__C FROM Project__c WHERE ProjectRef__c = 'TestRef'];
        
        System.assertEquals(1, prof.size());   
        
        System.assertEquals('Billed', prof[0].Status__C);
    }
    
    @isTest static void testCalloutFailure(){
        
        Test.setMock(WebServiceMock.class, new BillingCalloutServiceMockFailure()); 
        List<Project__c> prof = [SELECT Status__C FROM Project__c WHERE ProjectRef__c = 'TestRef'];
        System.assertEquals(1, prof.size());
        Test.startTest(); 
        prof[0].Status__c = 'Running';
        update prof;
        Test.stopTest();
        prof = [SELECT Status__C FROM Project__c WHERE ProjectRef__c = 'TestRef'];
        System.assertEquals(1, prof.size());   
        System.assertEquals('Running', prof[0].Status__C);
    }
    
}