unpackaged/objects/Scanned_Business_Cards__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Used for populating the Name of the Account as indicated on the business card.</description>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated based on matching logic</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scanned Business Cards</relationshipLabel>
        <relationshipName>Scanned_Business_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated based on matching logic</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Scanned Business Cards</relationshipLabel>
        <relationshipName>Scanned_Business_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Id__c</fullName>
        <description>Stores the external id of the user who created the record.</description>
        <externalId>true</externalId>
        <label>Created By Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Used for populating the Email of individual as indicated on the business card</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <description>Used for populating the Fax of individual as indicated on the business card</description>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for populating the First Name of individual as indicated on the business card</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>if(LEN( First_Name__c ) &gt; 0, &apos;Salutation &apos; + First_Name__c &amp; &quot;, &quot; , &quot;&quot; ) &amp;
if(LEN( Last_Name__c )&gt; 0, Last_Name__c  &amp; &quot;, &quot; , &quot;&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for populating the Last Name of individual as indicated on the business card</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Used for populating the Mobile of individual as indicated on the business card.</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Used for tracking notes associated to this business card</description>
        <label>Notes</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Used for populating the Phone of individual as indicated on the business card.</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>Used for populating the salutation of individual as indicated on the business card</description>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Country__c</fullName>
        <label>State / Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores the status of the business card. Incomplete indicates card has been scanned but not mapped to contact &amp; account, while complete indicates card is scanned and mapped to contact / account</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Used for populating the Title of individual as indicated on the business card</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Scanned Business Card</label>
    <nameField>
        <displayFormat>Card-{00000000}</displayFormat>
        <label>Card Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scanned Business Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/DTOScannedBusinessCard.cls
public class DTOScannedBusinessCard {
    
    public class CardsList {
        
        public List<CardItem> cardItemList = new List<CardItem>();
        
        public cardsList(List<Scanned_Business_Cards__c> someList) {
            
            for(Scanned_Business_Cards__c x :someList) {
                
                CardItem y = new CardItem(x.Id, 
                                          x.Account_Name__c, 
                                          x.Full_Name__c, 
                                          x.Status__c, 
                                          x.Title__c);
                
                cardItemList.add(y);
            }
            
        }       
        
    }
    
    
    public class CardItem {
        
        public String Id;
        public String accountName;
        public String fullName;
        public String status;
        public String title;
        
        public cardItem(String Id, String accountName, String fullName, String status, String title) {
            this.Id = Id;
            this.accountName = accountName;
            this.fullName = fullName;
            this.status = status;
            this.title = title;
        }
        
    }
    
    
    public class CardsList_2 {
        
        public List<CardItem_2> cardItemList = new List<CardItem_2>();
        
        public CardsList_2(List<Scanned_Business_Cards__c> someList) {
            
            for(Scanned_Business_Cards__c card :someList) {
                
                CardItem_2 cardItem = new CardItem_2(card.Account__c, 
                                                     card.Contact__c);
                
                cardItemList.add(cardItem);
            }
            
        }      
    }
    
    public class CardItem_2 {
        
        public String accountId;
        public String contactId;
        
        public CardItem_2(String accountId, String contactId) {
            
            this.accountId = accountId;
            this.contactId = contactId;
            
        }
    }
    
    public class Status_CardsIsCreated {
        
        public String code;
        public String id;
        
        public Status_CardsIsCreated( String code, String id ) {
            
            this.code = code;
            this.id = id;
            
        }
    }
    
    public class StatusMessage {
        
        public String message;
        public String errorCode;
        public String id;
        
        public StatusMessage( String message, String errorCode ) {
            
            this.message = message;
            this.errorCode = errorCode;
            
        }
        
        public StatusMessage( String message, String errorCode, String id ) {
            
            this.message = message;
            this.errorCode = errorCode;
            this.id = id;
            
        }
    }
    
    
    
        public class CardItemListFull {
        
        public List<CardItemFull> cardItemList = new List<CardItemFull>();
        
        public CardItemListFull(List<Scanned_Business_Cards__c> someList) {
            
            for(Scanned_Business_Cards__c card :someList) {
                
                CardItemFull cardItem = new CardItemFull(card.Id, card.Salutation__c, card.First_Name__c, 
                    									card.Last_Name__c, card.Account_Name__c,
                                                        card.Title__c, card.Phone__c,
                    									card.Mobile__c, card.Fax__c, card.Email__c, 
                    									card.Website__c, card.Street1__c, card.Street2__c, 
                    									card.City__c, card.State_Country__c, card.Country__c, 
                    									card.Postcode__c, card.Notes__c, card.Created_By_Id__c,
                                                        card.Status__c
                    );
                                
                cardItemList.add(cardItem);
                
                System.debug('126 cardItemList = ' + cardItemList);
            }
            
        }      
    }
    
    
     public class CardItemFull {
        
        public String cardId;
        public String salutation;
        public String firstName;
        public String lastName;
        public String accountName;
        public String title;
        public String phone;
        public String mobile;
        public String fax;
        public String email;
        public String website;
        public String street1;
        public String street2;
        public String city;
        public String stateCountry;
        public String country;
        public String postcode;
        public String notes;
        public String createdById;
        public String status;   
        
        public CardItemFull ( String cardId, String salutation, String firstName, String lastName, String accountName,
                                       String title, String phone, String mobile, String fax, String email, String website, String street1,
                                       String street2, String city, String stateCountry, String country, String postcode, String notes,
                                       String createdById, String status) {
                                           
                                           this.cardId = cardId;
                                           this.salutation = salutation;
                                           this.firstName = firstName;
                                           this.lastName = lastName;
                                           this.accountName = accountName;
                                           this.title = title;
                                           this.phone = phone;
                                           this.mobile = mobile;
                                           this.fax = fax;
                                           this.email = email;
                                           this.website = website;
                                           this.street1 = street1;
                                           this.street2 = street2;
                                           this.city = city;
                                           this.stateCountry = stateCountry;
                                           this.country = country;
                                           this.postcode = postcode;
                                           this.notes = notes;
                                           this.createdById = createdById;
                                           this.status = status;
                                           
                                       }
    }
    
    public class GeneralResponse {
        
        public String descriptionOfResult;
        
        public GeneralResponse (String descriptionOfResult) {
            
            this.descriptionOfResult = descriptionOfResult;
            
        }
        
    }
    
}