unpackaged/objects/Scanned_Business_Cards__c.object
<CustomObject>
    <fields>
        <fullName>Created_By_Id__c</fullName>
        <description>Stores the external id of the user who created the record.</description>
        <externalId>true</externalId>
        <label>Created By Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scanned Business Card</label>
    <nameField>
        <displayFormat>Card-{00000000}</displayFormat>
        <label>Card Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scanned Business Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CardWrapper.cls
global class CardWrapper implements Comparable {
    
    public Scanned_Business_Cards__c card;
    
    public CardWrapper(Scanned_Business_Cards__c c) {
        card = c;
    }
    
    global Integer compareTo(Object compareTo) {
        CardWrapper compareToCard = (CardWrapper)compareTo;
        
        Integer returnValue = 0;
        if (card.Created_By_Id__c > compareToCard.card.Created_By_Id__c) {
            returnValue = 1;
        } else if (card.Created_By_Id__c < compareToCard.card.Created_By_Id__c) {
            returnValue = -1;
        }
        
        return returnValue;       
    }
}