unpackaged/objects/Scanned_Business_Cards__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Used for populating the Name of the Account as indicated on the business card.</description>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated based on matching logic</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scanned Business Cards</relationshipLabel>
        <relationshipName>Scanned_Business_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated based on matching logic</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Scanned Business Cards</relationshipLabel>
        <relationshipName>Scanned_Business_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Id__c</fullName>
        <description>Stores the external id of the user who created the record.</description>
        <externalId>true</externalId>
        <label>Created By Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Used for populating the Email of individual as indicated on the business card</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <description>Used for populating the Fax of individual as indicated on the business card</description>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for populating the First Name of individual as indicated on the business card</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>if(LEN( First_Name__c ) &gt; 0, &apos;Salutation &apos; + First_Name__c &amp; &quot;, &quot; , &quot;&quot; ) &amp;
if(LEN( Last_Name__c )&gt; 0, Last_Name__c  &amp; &quot;, &quot; , &quot;&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for populating the Last Name of individual as indicated on the business card</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Used for populating the Mobile of individual as indicated on the business card.</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Used for tracking notes associated to this business card</description>
        <label>Notes</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Used for populating the Phone of individual as indicated on the business card.</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>Used for populating the salutation of individual as indicated on the business card</description>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Country__c</fullName>
        <label>State / Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores the status of the business card. Incomplete indicates card has been scanned but not mapped to contact &amp; account, while complete indicates card is scanned and mapped to contact / account</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Used for populating the Title of individual as indicated on the business card</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Scanned Business Card</label>
    <nameField>
        <displayFormat>Card-{00000000}</displayFormat>
        <label>Card Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scanned Business Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ScannedBusinessCardDAO.cls
public class ScannedBusinessCardDAO {
    
    public static List<Scanned_Business_Cards__c> getBusinessCardByCreatedByIdAndStatus(String userId, String status) {
        
        List<Scanned_Business_Cards__c> result = new List<Scanned_Business_Cards__c>();
        
        result = [SELECT Created_By_Id__c,
                  Account_Name__c,
                  Full_Name__c, Status__c,
                  Title__c
                  FROM Scanned_Business_Cards__c
                  WHERE Status__c = :status
                  AND Created_By_Id__c = :userId];
        
        return result;
        
    }
    
    public static List<Scanned_Business_Cards__c> getCardByCardId(String cardId) {
        
        List<Scanned_Business_Cards__c> result = new List<Scanned_Business_Cards__c>();
        
        result = [SELECT Id, Salutation__c,
                  First_Name__c, Last_Name__c,
                  Account_Name__c,
                  Title__c, Phone__c,
                  Mobile__c, Fax__c, Email__c, 
                  Website__c, Street1__c, Street2__c, 
                  City__c, State_Country__c, Country__c, 
                  Postcode__c, Notes__c, Created_By_Id__c,
                  Status__c
                  FROM Scanned_Business_Cards__c
                  WHERE Id = :cardId];
        
        return result;
        
    }
    
    public static List<Scanned_Business_Cards__c> getCard() {
        return new List<Scanned_Business_Cards__c>([SELECT Name, Account_Name__c,
                                                    Created_By_Id__c, First_Name__c, Last_Name__c,
                                                    Contact__c, Account__c
                                                    FROM Scanned_Business_Cards__c]);
    }
    
    public static List<Scanned_Business_Cards__c> getCardByContactLookup(List<Contact> oldList) {
        return new List<Scanned_Business_Cards__c>([SELECT Contact__c FROM Scanned_Business_Cards__c WHERE Contact__c IN :oldList]);
    }
                                                    
    public static List<Scanned_Business_Cards__c> getCardByAccountLookup(List<Account> oldList) {
        return new List<Scanned_Business_Cards__c>([SELECT Account__c FROM Scanned_Business_Cards__c WHERE Account__c IN :oldList]);
    }
    
    public static List<Scanned_Business_Cards__c> getCard_SortByCreatorId() {
        return new List<Scanned_Business_Cards__c>([SELECT Name, Account_Name__c,
                                                    Created_By_Id__c, First_Name__c, Last_Name__c,
                                                    Contact__c, Account__c
                                                    FROM Scanned_Business_Cards__c
                                                    ORDER BY Created_By_Id__c LIMIT 20]);
    }
    
    public static List<Scanned_Business_Cards__c> getCard_SortByAccountName() {
        return new List<Scanned_Business_Cards__c>([SELECT Name, Account_Name__c,
                                                    Created_By_Id__c, First_Name__c, Last_Name__c,
                                                    Contact__c, Account__c
                                                    FROM Scanned_Business_Cards__c
                                                    ORDER BY Account_Name__c DESC LIMIT 20]);
    }
    
    public static List<Scanned_Business_Cards__c> getCard_SortByContactLastName() {
        return new List<Scanned_Business_Cards__c>([SELECT Name, Account_Name__c,
                                                    Created_By_Id__c, First_Name__c, Last_Name__c,
                                                    Contact__c, Account__c
                                                    FROM Scanned_Business_Cards__c
                                                    ORDER BY Last_Name__c DESC LIMIT 20]);
    }
    
    public static List<Scanned_Business_Cards__c> getCard_DynamicSort(String sortFullExp) {
        List<Scanned_Business_Cards__c> sortedCards = new List<Scanned_Business_Cards__c>();
        
        for(Scanned_Business_Cards__c cardItem :Database.query('SELECT Name, Account_Name__c,' + 
                                                               ' Created_By_Id__c, First_Name__c, Last_Name__c,' + 
                                                               ' Contact__c, Account__c FROM Scanned_Business_Cards__c' +
                                                               ' ORDER BY ' +  sortFullExp + ' LIMIT 20')) {
            sortedCards.add(cardItem);
      }
        return sortedCards;
    }
    
    public static List<Scanned_Business_Cards__c> getCard_DynamicSearch(String searchString) {
        List<Scanned_Business_Cards__c> foundCards = new List<Scanned_Business_Cards__c>();
        
        for(Scanned_Business_Cards__c cardItem :Database.query('SELECT Name, Account_Name__c,' + 
                                                               ' Created_By_Id__c, First_Name__c, Last_Name__c,' + 
                                                               ' Contact__c, Account__c FROM Scanned_Business_Cards__c' +
                                                               ' WHERE  Account_Name__c LIKE \'%' 
                                                               + searchString + '%\' LIMIT 20')) {
          foundCards.add(cardItem);
        }
        return foundCards;
    }
    
    public static List<Contact> getContact_ByFirstNameAndLastName(List<String> names, List<String> surnames) {
        return [SELECT Id FROM Contact WHERE FirstName IN :names AND LastName IN :surnames
                                         ORDER BY CreatedDate DESC LIMIT 1];
    }
    
    public static List<Account> getAccount_ByName(Map<String, Id> accountName2cardId) {
        return [SELECT Id FROM Account WHERE Name IN :accountName2cardId.keySet() ORDER BY CreatedDate DESC LIMIT 1];
    }
}